[pytest]
markers =
    usuarios: testes automatizados do endpoint de usuários da ServeRest
    login: testes automatizados do endpoint de login da ServeRest
    produtos: testes automatizados do endpoint de produtos da ServeRest
    carrinhos: testes automatizados do endpoint de carrinhos da ServeRest